version: "3.6"

services:
  app:
    image: ${REGISTRY}/votingapp:${TAG}
    build:
      context: .
      dockerfile: ${VOTINGAPP_API}Dockerfile
      args:
        api: ${VOTINGAPP_API}
        domain: ${VOTINGAPP_DOMAIN}
        tests: ${VOTINGAPP_TESTS}
    container_name: votingapp
    ports:
      - 8080:80
  #   environment: 
  #     mongodb: "mongodb://mongo:27017"

  # mongo:
  #   image: mongo

  integration-tests:
    image: ${REGISTRY}/integration-tests:${TAG}
    build:
      context: .
      dockerfile: ${VOTINGAPP_INTEGRATION_TESTS}Dockerfile
      args:
        tests: ${VOTINGAPP_INTEGRATION_TESTS}
    container_name: integration-tests